const app=document.querySelector('#app');
const state={step:0,company:'',trade:'Landscaping / Hardscape',wage:22,burden:7,crew:3,target:40,overhead:10,planned:2900,hours:18,materials:900,equipment:100,other:150,actualHours:21,actualMaterials:980};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0);
const num=(k,v)=>{state[k]=Number(v)||0;render()};
const text=(k,v)=>{state[k]=v};
function calc(){const loaded=(state.wage+state.burden)*state.crew;const labor=loaded*state.hours;const direct=labor+state.materials+state.equipment+state.other;const cost=direct*(1+state.overhead/100);const rec=state.target>=100?cost:cost/(1-state.target/100);const plannedMargin=state.planned?((state.planned-cost)/state.planned)*100:0;const actualLabor=loaded*state.actualHours;const actualCost=(actualLabor+state.actualMaterials+state.equipment+state.other)*(1+state.overhead/100);return{loaded,labor,cost,rec,plannedMargin,actualCost,actualProfit:state.planned-actualCost}}
function input(label,key,type='number'){return `<label>${label}<input type="${type}" value="${state[key]}" oninput="${type==='text'?`window.txt('${key}',this.value)`:`window.n('${key}',this.value)`}"></label>`}
function layout(body){app.innerHTML=`<main><header><div><b>JOBVERO</b><small>PRIVATE BETA</small></div><span>Founding Contractor Program</span></header>${body}<footer>Jobvero beta • Built to validate real estimating decisions, not replace your current software.</footer></main>`}
function render(){const c=calc();if(state.step===0)return layout(`<section class="hero"><div><p class="eyebrow">FOUNDING CONTRACTOR BETA</p><h1>Know what the job should make <em>before</em> you quote it.</h1><p class="lead">Jobvero uses your actual labor, materials, overhead and target margin to catch underpriced work before the estimate goes out.</p><button onclick="window.go(1)">Start free contractor test →</button><p class="fine">No credit card. Use one real upcoming estimate.</p></div><div class="phone"><span>TRUE JOB COST</span><b>$2,126</b><span>PLANNED PRICE</span><b>$2,900</b><div class="alert">Below your target margin</div><span>JOBVERO RECOMMENDATION</span><strong>$3,550</strong></div></section>`);
if(state.step===1)return layout(`<section class="card"><p class="eyebrow">STEP 1 OF 4</p><h2>Teach Jobvero your business.</h2><p>These numbers stay company-specific. We don't use generic industry pricing as your answer.</p><div class="grid">${input('Company name','company','text')}<label>Primary trade<select onchange="window.txt('trade',this.value)"><option>Landscaping / Hardscape</option><option>Concrete / Pavers</option><option>Painting</option><option>Pressure Washing</option><option>Remodeling / Handyman</option></select></label>${input('Average wage / field employee','wage')}${input('Payroll burden / employee-hour','burden')}${input('Typical crew size','crew')}${input('Target gross margin %','target')}${input('Overhead allocation %','overhead')}</div><div class="insight">Loaded crew labor cost: <b>${money(c.loaded)} per crew-hour</b></div><button onclick="window.go(2)">Price a real job →</button></section>`);
if(state.step===2)return layout(`<section class="card"><p class="eyebrow">STEP 2 OF 4</p><h2>Price a real upcoming job.</h2><p>Enter what you were already planning to charge. Jobvero is the second opinion.</p><div class="grid">${input('Planned customer price','planned')}${input('Estimated crew-hours','hours')}${input('Materials','materials')}${input('Equipment','equipment')}${input('Dump / subs / other','other')}</div><div class="metrics"><div><span>TRUE COST</span><b>${money(c.cost)}</b></div><div><span>PLANNED MARGIN</span><b>${c.plannedMargin.toFixed(1)}%</b></div><div class="focus"><span>RECOMMENDED BID</span><b>${money(Math.ceil(c.rec/50)*50)}</b></div></div>${c.plannedMargin<state.target?`<div class="warning">At <b>${money(state.planned)}</b>, this job is projected at about <b>${c.plannedMargin.toFixed(0)}%</b> gross margin—not your ${state.target}% target.</div>`:''}<details><summary>Show how Jobvero calculated this</summary><p>Labor ${money(c.labor)} + materials ${money(state.materials)} + equipment ${money(state.equipment)} + other ${money(state.other)}, then ${state.overhead}% overhead. Recommended price is the amount required for the ${state.target}% target margin.</p></details><button onclick="window.go(3)">Save & close job later →</button></section>`);
if(state.step===3)return layout(`<section class="card"><p class="eyebrow">STEP 3 OF 4</p><h2>What actually happened?</h2><p>When the job is finished, close the loop. This is what eventually makes Jobvero company-specific.</p><div class="grid">${input('Actual crew-hours','actualHours')}${input('Actual materials','actualMaterials')}</div><div class="metrics"><div><span>ESTIMATED COST</span><b>${money(c.cost)}</b></div><div><span>ACTUAL COST</span><b>${money(c.actualCost)}</b></div><div class="focus"><span>ACTUAL PROFIT</span><b>${money(c.actualProfit)}</b></div></div><div class="warning">Labor used <b>${(((state.actualHours-state.hours)/state.hours)*100).toFixed(0)}% more crew-hours</b> than estimated. Repeated misses like this become a warning on future similar estimates.</div><button onclick="window.go(4)">See what Jobvero learned →</button></section>`);
layout(`<section class="card"><p class="eyebrow">STEP 4 OF 4</p><h2>Make the next quote smarter.</h2><div class="learn"><span>THIS JOB</span><b>${state.hours} estimated → ${state.actualHours} actual crew-hours</b><span>NEXT-JOB CANDIDATE</span><strong>${((state.hours+state.actualHours)/2).toFixed(1)} crew-hours</strong></div><h3>Founding tester question</h3><p class="question">If Jobvero prevented one underbid like this each month, would you keep using it for <b>$59/month?</b></p><div class="choices"><button>Yes</button><button class="light">Maybe</button><button class="light">No</button></div><p class="fine">Production beta will save each company's estimates securely and learn only from that company's completed jobs.</p></section>`)}
window.go=n=>{state.step=n;scrollTo(0,0);render()};window.n=num;window.txt=text;render();
