const weeks=[
{week:1,date:"Sunday, September 20",games:[["7:00 PM","Ball Busters vs Has Been Again","Bat Intentions vs City Boyz"],["8:00 PM","Balls Deep vs City Boyz","Ball Busters vs Free Agent Team"],["9:00 PM","Balls Deep vs Has Been Again","Bat Intentions vs Free Agent Team"]]},
{week:2,date:"Sunday, September 27",games:[["7:00 PM","Balls Deep vs Free Agent Team","Has Been Again vs City Boyz"],["8:00 PM","Ball Busters vs Bat Intentions","Has Been Again vs Free Agent Team"],["9:00 PM","Balls Deep vs Bat Intentions","Ball Busters vs City Boyz"]]},
{week:3,date:"Sunday, October 4",games:[["7:00 PM","Ball Busters vs Balls Deep","Bat Intentions vs Free Agent Team"],["8:00 PM","Free Agent Team vs City Boyz","Has Been Again vs Bat Intentions"],["9:00 PM","Ball Busters vs Has Been Again","Balls Deep vs City Boyz"]]},
{week:4,date:"Sunday, October 11",games:[["7:00 PM","Has Been Again vs City Boyz","Ball Busters vs Free Agent Team"],["8:00 PM","Balls Deep vs Has Been Again","Ball Busters vs Bat Intentions"],["9:00 PM","Bat Intentions vs City Boyz","Balls Deep vs Free Agent Team"]]},
{week:5,date:"Sunday, October 18",games:[["7:00 PM","Bat Intentions vs Free Agent Team","Balls Deep vs City Boyz"],["8:00 PM","Has Been Again vs Free Agent Team","Ball Busters vs City Boyz"],["9:00 PM","Balls Deep vs Bat Intentions","Ball Busters vs Has Been Again"]]},
{week:6,date:"Sunday, October 25",games:[["7:00 PM","Has Been Again vs Bat Intentions","Ball Busters vs Balls Deep"],["8:00 PM","Balls Deep vs Free Agent Team","Bat Intentions vs City Boyz"],["9:00 PM","Ball Busters vs Free Agent Team","Has Been Again vs City Boyz"]]},
{week:7,date:"Sunday, November 1",games:[["7:00 PM","Has Been Again vs Free Agent Team","Balls Deep vs Bat Intentions"],["8:00 PM","Ball Busters vs City Boyz","Balls Deep vs Has Been Again"],["9:00 PM","Ball Busters vs Bat Intentions","Free Agent Team vs City Boyz"]]}
];
const playoffs=[["7:00 PM","Quarterfinal #1 — #3 vs #6","Quarterfinal #2 — #4 vs #5"],["8:00 PM","Semifinal #1 — #1 vs Winner QF #2","Semifinal #2 — #2 vs Winner QF #1"],["9:00 PM","CHAMPIONSHIP — Winners of Semifinals","3RD PLACE — Losers of Semifinals"]];
const teams=["Ball Busters","Balls Deep","Has Been Again","Bat Intentions","Free Agent Team","City Boyz"];
const card={background:"#fff",border:"1px solid #e5e7eb",borderRadius:16,overflow:"hidden",boxShadow:"0 8px 24px rgba(0,0,0,.08)"};
export default function FallSoftballSchedule(){return <div style={{minHeight:"100vh",background:"#f4f1ea",padding:"24px 14px",fontFamily:"Arial,Helvetica,sans-serif",color:"#172033"}}><main style={{maxWidth:1100,margin:"0 auto"}}><header style={{background:"linear-gradient(135deg,#111827,#26354a)",color:"#fff",padding:"28px 20px",borderRadius:18,textAlign:"center",marginBottom:18}}><div style={{color:"#f59e0b",fontWeight:900,letterSpacing:2,fontSize:13}}>DESERT REC SPORTS LEAGUE</div><h1 style={{margin:"7px 0",fontSize:"clamp(30px,5vw,48px)"}}>Sunday Softball League</h1><div style={{fontSize:20,fontWeight:900,color:"#fb923c"}}>Fall 2026 Season Schedule</div><p style={{margin:"10px 0 0"}}>Earl Edgar Park · Buckeye, AZ · Fields 1 & 2 · 7–10 PM · Doubleheaders</p></header><div style={{display:"flex",gap:8,flexWrap:"wrap",justifyContent:"center",marginBottom:20}}>{teams.map(t=><span key={t} style={{padding:"9px 12px",borderRadius:999,background:"#111827",color:"#fff",fontWeight:800,fontSize:13}}>{t}</span>)}</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(330px,1fr))",gap:16}}>{weeks.map(w=><Week key={w.week} title={`Week ${w.week} — ${w.date}`} games={w.games}/>) }<Week title="Week 8 — Sunday, November 8 · PLAYOFFS" games={playoffs}/></div><section style={{...card,marginTop:18,padding:20}}><h3 style={{marginTop:0}}>League Info</h3><p style={{lineHeight:1.65,marginBottom:0}}>6 teams · 7 regular-season weeks + Week 8 playoffs · Doubleheaders each Sunday · All teams make the playoffs · #1 and #2 receive first-round byes · Higher seed is home team. Schedule subject to change.</p></section><div style={{textAlign:"center",margin:"22px 0"}}><a href="/" style={{display:"inline-block",padding:"12px 18px",background:"#c76a28",color:"#fff",borderRadius:10,textDecoration:"none",fontWeight:900}}>Back to Desert Rec Home</a></div></main></div>}
function Week({title,games}){return <section style={card}><div style={{background:"#111827",color:"#fb923c",padding:"13px 15px",fontWeight:900,textAlign:"center"}}>{title}</div><div style={{display:"grid",gridTemplateColumns:"78px 1fr 1fr",background:"#26354a",color:"#fff",fontWeight:800,fontSize:12}}><div style={{padding:9}}>TIME</div><div style={{padding:9}}>FIELD 1</div><div style={{padding:9}}>FIELD 2</div></div>{games.map((g,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"78px 1fr 1fr",borderTop:"1px solid #e5e7eb",fontSize:13}}><div style={{padding:10,fontWeight:900}}>{g[0]}</div><div style={{padding:10,fontWeight:700}}>{g[1]}</div><div style={{padding:10,fontWeight:700}}>{g[2]}</div></div>)}</section>}