import { useEffect, useMemo, useState } from "react";
import { supabase } from "./supabaseClient";
const ADMIN_EMAIL="desertrecsportsleague@gmail.com";

function roundRobin(teams){
  const list=[...teams]; if(list.length%2) list.push(null); const n=list.length; const rounds=[]; let arr=[...list];
  for(let r=0;r<n-1;r++){const pairs=[];for(let i=0;i<n/2;i++){const a=arr[i],b=arr[n-1-i];if(a&&b)pairs.push([a,b]);}rounds.push(pairs);arr=[arr[0],arr[n-1],...arr.slice(1,n-1)];}
  return rounds;
}

export default function JarvisScheduleManager(){
 const [allowed,setAllowed]=useState(false),[seasons,setSeasons]=useState([]),[seasonKey,setSeasonKey]=useState(""),[teams,setTeams]=useState([]),[constraints,setConstraints]=useState([]),[proposal,setProposal]=useState(null),[message,setMessage]=useState("");
 const [settings,setSettings]=useState({weeks:7,meetings:2,times:"6:00 PM,7:00 PM,8:00 PM,9:00 PM",fields:"Field 1,Field 2",start_date:""});
 async function loadSeasons(){const {data}=await supabase.from("seasons").select("season_key,name,start_date,status").order("start_date",{ascending:false});setSeasons(data||[]);const first=(data||[]).find(x=>x.status==="active")||(data||[])[0];if(first){setSeasonKey(first.season_key);setSettings(s=>({...s,start_date:first.start_date||""}));}}
 useEffect(()=>{supabase.auth.getUser().then(async({data})=>{const ok=(data?.user?.email||"").toLowerCase()===ADMIN_EMAIL;setAllowed(ok);if(ok)await loadSeasons();});},[]);
 useEffect(()=>{if(!seasonKey)return;(async()=>{const [{data:t},{data:c}]=await Promise.all([supabase.from("teams").select("id,team_name").eq("season_key",seasonKey).order("team_name"),supabase.from("schedule_constraints").select("id,team_id,constraint_type,value,priority,active").eq("season_key",seasonKey).eq("active",true)]);setTeams(t||[]);setConstraints(c||[]);})();},[seasonKey]);
 const teamMap=useMemo(()=>Object.fromEntries(teams.map(t=>[t.id,t.team_name])),[teams]);
 if(!allowed)return null;
 function generate(){
  if(teams.length<2)return setMessage("This season needs at least 2 teams before Jarvis can generate a schedule.");
  const times=settings.times.split(",").map(x=>x.trim()).filter(Boolean),fields=settings.fields.split(",").map(x=>x.trim()).filter(Boolean); if(!times.length||!fields.length)return setMessage("Add at least one time and field.");
  const base=roundRobin(teams),meetings=Math.max(1,Number(settings.meetings)||1),weeks=Math.max(1,Number(settings.weeks)||1),allRounds=[];for(let m=0;m<meetings;m++)base.forEach((round,idx)=>allRounds.push({round:idx,pairs:m%2?round.map(([a,b])=>[b,a]):round}));
  const earlyCount={},lateCount={},games=[],conflicts=[]; teams.forEach(t=>{earlyCount[t.id]=0;lateCount[t.id]=0;});
  const allowedByTeam={};constraints.filter(c=>c.constraint_type==="allowed_times").forEach(c=>allowedByTeam[c.team_id]=c.value?.times||[]);
  const start=settings.start_date?new Date(`${settings.start_date}T12:00:00`):null;
  allRounds.slice(0,weeks).forEach((rd,w)=>{const slots=[];times.forEach(time=>fields.forEach(field=>slots.push({time,field})));rd.pairs.forEach(([home,away],i)=>{let candidates=slots.filter(s=>{const ah=allowedByTeam[home.id],aa=allowedByTeam[away.id];return (!ah?.length||ah.includes(s.time))&&(!aa?.length||aa.includes(s.time));});if(!candidates.length){conflicts.push(`Week ${w+1}: no allowed time found for ${home.team_name} vs ${away.team_name}`);candidates=slots;}candidates.sort((a,b)=>(earlyCount[home.id]+earlyCount[away.id])-(earlyCount[home.id]+earlyCount[away.id]));const slot=candidates[i%candidates.length]||slots[i%slots.length];if(slot.time===times[0]){earlyCount[home.id]++;earlyCount[away.id]++;}if(slot.time===times[times.length-1]){lateCount[home.id]++;lateCount[away.id]++;}let date="";if(start){const d=new Date(start);d.setDate(d.getDate()+w*7);date=d.toISOString().slice(0,10);}games.push({week:w+1,game_date:date,game_time:slot.time,field:slot.field,home_team_id:home.id,away_team_id:away.id,home:home.team_name,away:away.team_name});});});
  setProposal({games,conflicts,earlyCount,lateCount});setMessage(`Proposal generated: ${games.length} games. Current live schedule was NOT changed.`);
 }
 async function saveProposal(){if(!proposal)return;const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from("schedule_proposals").insert({season_key:seasonKey,status:"proposed",settings,generated_schedule:proposal.games,conflicts:proposal.conflicts,requested_by:user?.id||null});if(error)return setMessage(error.message);setMessage("Schedule proposal saved for review. Live schedule still unchanged.");}
 return <section style={{marginTop:20,padding:18,border:"2px solid #8b5cf6",borderRadius:16,background:"#fff"}}><div style={{fontSize:12,fontWeight:900,color:"#6d28d9",letterSpacing:1}}>JARVIS SCHEDULING ENGINE</div><h2 style={{margin:"5px 0"}}>Constraint-Based Schedule Proposal</h2><p style={{color:"#6b7280"}}>Testing mode: Jarvis can generate and save proposals, but this screen cannot overwrite the published schedule.</p>{message&&<div style={{padding:10,background:"#f3f4f6",borderRadius:10,fontWeight:700}}>{message}</div>}
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:8,marginTop:12}}><select value={seasonKey} onChange={e=>{setSeasonKey(e.target.value);setProposal(null);const s=seasons.find(x=>x.season_key===e.target.value);setSettings(v=>({...v,start_date:s?.start_date||""}));}}>{seasons.map(s=><option key={s.season_key} value={s.season_key}>{s.name}</option>)}</select><input type="number" min="1" value={settings.weeks} onChange={e=>setSettings({...settings,weeks:e.target.value})} placeholder="Weeks"/><input type="number" min="1" value={settings.meetings} onChange={e=>setSettings({...settings,meetings:e.target.value})} placeholder="Meetings per opponent"/><input type="date" value={settings.start_date} onChange={e=>setSettings({...settings,start_date:e.target.value})}/><input value={settings.times} onChange={e=>setSettings({...settings,times:e.target.value})} placeholder="Times, comma separated"/><input value={settings.fields} onChange={e=>setSettings({...settings,fields:e.target.value})} placeholder="Fields, comma separated"/></div>
 <p><strong>{teams.length} teams</strong> · {constraints.length} active constraint(s)</p>{constraints.length>0&&<div style={{fontSize:13,background:"#faf5ff",padding:10,borderRadius:10}}>{constraints.map(c=><div key={c.id}><strong>{teamMap[c.team_id]||"League"}</strong>: {c.constraint_type} {JSON.stringify(c.value)} · priority {c.priority}</div>)}</div>}
 <button onClick={generate} style={{marginTop:10,padding:"10px 14px",background:"#8b5cf6",color:"white",border:0,borderRadius:10,fontWeight:900}}>Generate Proposal</button>
 {proposal&&<div style={{marginTop:14}}><h3>Proposal Preview</h3>{proposal.conflicts.length>0&&<div style={{padding:10,background:"#fef2f2",borderRadius:10}}><strong>Conflicts:</strong>{proposal.conflicts.map((x,i)=><div key={i}>{x}</div>)}</div>}<div style={{maxHeight:360,overflow:"auto",marginTop:8}}>{proposal.games.map((g,i)=><div key={i} style={{padding:8,borderBottom:"1px solid #e5e7eb"}}>W{g.week} · {g.game_date||"date TBD"} · {g.game_time} · {g.field} — <strong>{g.home}</strong> vs <strong>{g.away}</strong></div>)}</div><button onClick={saveProposal} style={{marginTop:10,padding:"9px 14px",background:"#111827",color:"white",border:0,borderRadius:9,fontWeight:900}}>Save Proposal for Review</button></div>}
 </section>;
}
