import { useEffect, useMemo, useState } from "react";
import { supabase } from "./supabaseClient";

function money(cents){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format((cents||0)/100)}

export function TournamentPublic(){
 const [list,setList]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState({team_name:"",captain_name:"",captain_email:"",captain_phone:""}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{const {data,error}=await supabase.rpc("list_public_tournaments");if(!error)setList(data||[]);})();},[]);
 useEffect(()=>{const p=new URLSearchParams(location.search);const key=p.get("tournament");if(key)loadTournament(key);},[]);
 async function loadTournament(key){const {data,error}=await supabase.rpc("get_public_tournament",{p_key:key});if(error)return setMessage(error.message);setSelected(data?.[0]||null)}
 const spots=useMemo(()=>selected?Math.max((selected.team_cap||0)-(selected.paid_teams||0),0):0,[selected]);
 async function checkout(e){e.preventDefault();if(!selected)return;setBusy(true);setMessage("");try{const origin=location.origin;const success=`${origin}${location.pathname}?tournament=${encodeURIComponent(selected.tournament_key)}&payment=success`;const cancel=`${origin}${location.pathname}?tournament=${encodeURIComponent(selected.tournament_key)}&payment=cancelled`;const {data,error}=await supabase.functions.invoke("tournament-checkout",{body:{tournament_key:selected.tournament_key,...form,success_url:success,cancel_url:cancel}});if(error)throw error;if(data?.error)throw new Error(data.error);if(!data?.url)throw new Error("Checkout URL was not returned.");location.href=data.url;}catch(err){setMessage(err?.message||String(err));setBusy(false)}}
 const params=new URLSearchParams(location.search); const payment=params.get("payment");
 if(selected)return <div className="page"><button onClick={()=>{setSelected(null);history.replaceState({},"",location.pathname)}}>← Back to tournaments</button><h2 className="section-title">{selected.name}</h2><div className="card"><div><strong>{selected.event_date}</strong> · {selected.start_time}-{selected.end_time}</div><div>{selected.location}, {selected.city}</div><div>{selected.guaranteed_games} games guaranteed · {selected.format}</div><div>{selected.prize_text}</div><div style={{marginTop:8,fontWeight:900}}>{selected.paid_teams}/{selected.team_cap} paid teams · {spots} spots left</div></div>{payment==="success"&&<div className="card" style={{border:"2px solid #16a34a"}}><strong>Payment completed.</strong><p>Your team will appear once Stripe finishes the confirmation webhook. You’ll receive a roster/waiver link after confirmation.</p></div>}{payment==="cancelled"&&<div className="card"><strong>Checkout cancelled.</strong> Your team was not registered and no spot was taken.</div>}{selected.registration_enabled&&spots>0?<div className="card"><h3>Team Registration</h3><p>Registration is not complete until payment succeeds. Only paid teams count toward the {selected.team_cap}-team cap.</p><form className="form" onSubmit={checkout}><input required placeholder="Team Name" value={form.team_name} onChange={e=>setForm({...form,team_name:e.target.value})}/><input required placeholder="Captain Name" value={form.captain_name} onChange={e=>setForm({...form,captain_name:e.target.value})}/><input required type="email" placeholder="Captain Email" value={form.captain_email} onChange={e=>setForm({...form,captain_email:e.target.value})}/><input placeholder="Captain Phone" value={form.captain_phone} onChange={e=>setForm({...form,captain_phone:e.target.value})}/>{selected.rules_text&&<div style={{whiteSpace:"pre-wrap",padding:12,background:"#f8fafc",borderRadius:12}}>{selected.rules_text}</div>}<button disabled={busy} className="primary">{busy?"Opening Checkout…":`Pay ${money(selected.entry_fee_cents)} & Register Team`}</button></form>{message&&<p style={{color:"#b91c1c",fontWeight:700}}>{message}</p>}</div>:<div className="card"><strong>{spots===0?"Tournament is sold out.":"Registration is currently closed."}</strong></div>}</div>;
 return <div className="page"><h2 className="section-title">One-Day Tournaments</h2><p className="section-subtitle">Register and pay for upcoming Desert Rec tournaments.</p>{!list.length?<div className="card">No public tournaments are available yet.</div>:<div className="grid2">{list.map(t=><div className="card" key={t.tournament_key}><h3>{t.name}</h3><p>{t.event_date} · {t.location}, {t.city}</p><p>{t.guaranteed_games} games guaranteed · {t.prize_text||""}</p><p><strong>{money(t.entry_fee_cents)}</strong> per team · {t.paid_teams}/{t.team_cap} paid</p><button className="primary" onClick={()=>loadTournament(t.tournament_key)}>View Tournament</button></div>)}</div>}</div>
}

export function TournamentRoster(){
 const [token,setToken]=useState(""),[data,setData]=useState(null),[message,setMessage]=useState(""),[player,setPlayer]=useState({player_name:"",player_email:"",player_phone:""}),[signature,setSignature]=useState({});
 useEffect(()=>{const p=new URLSearchParams(location.search);const t=p.get("roster");if(t){setToken(t);load(t)}},[]);
 async function call(action,payload={}){const {data,error}=await supabase.functions.invoke("tournament-roster",{body:{token,action,...payload}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
 async function load(t=token){try{const {data,error}=await supabase.functions.invoke("tournament-roster",{body:{token:t,action:"load"}});if(error)throw error;if(data?.error)throw new Error(data.error);setData(data);setMessage("")}catch(e){setMessage(e?.message||String(e))}}
 async function add(e){e.preventDefault();try{await call("add",{player});setPlayer({player_name:"",player_email:"",player_phone:""});await load();}catch(e){setMessage(e?.message||String(e))}}
 async function sign(p){try{const sig=signature[p.id]||"";if(!sig.trim())throw new Error("Type the player’s full legal name.");await call("waiver",{player:{id:p.id,signature:sig.trim()}});await load();}catch(e){setMessage(e?.message||String(e))}}
 return <div className="page"><h2 className="section-title">Tournament Roster & Waivers</h2>{!data?<div className="card"><form className="form" onSubmit={e=>{e.preventDefault();load()}}><input placeholder="Roster access token" value={token} onChange={e=>setToken(e.target.value)}/><button className="primary">Open Roster</button></form>{message&&<p style={{color:"#b91c1c"}}>{message}</p>}</div>:<><div className="card"><h3>{data.registration.team_name}</h3><p>Captain: {data.registration.captain_name}</p></div><div className="card"><h3>Add Player</h3><form className="form" onSubmit={add}><input required placeholder="Player Name" value={player.player_name} onChange={e=>setPlayer({...player,player_name:e.target.value})}/><input placeholder="Player Email" value={player.player_email} onChange={e=>setPlayer({...player,player_email:e.target.value})}/><input placeholder="Player Phone" value={player.player_phone} onChange={e=>setPlayer({...player,player_phone:e.target.value})}/><button className="primary">Add Player</button></form></div><div className="card"><h3>Players & Waivers</h3>{!data.players.length?<p>No players added yet.</p>:data.players.map(p=><div key={p.id} style={{padding:"12px 0",borderBottom:"1px solid #e5e7eb"}}><strong>{p.player_name}</strong> · {p.waiver_signed?"Waiver signed":"Waiver required"}{!p.waiver_signed&&<div className="row" style={{marginTop:8}}><input placeholder="Full legal name as signature" value={signature[p.id]||""} onChange={e=>setSignature({...signature,[p.id]:e.target.value})}/><button onClick={()=>sign(p)}>Sign Waiver</button></div>}</div>)}</div>{message&&<p style={{color:"#b91c1c"}}>{message}</p>}</>}</div>
}
